name: Deployment pipeline

env:
  CONDITION: ${{ contains(join(toJson(github.event.commits.*.message), ','),'#skip') }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  checkout-and-test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: bloglist_db
          POSTGRES_PASSWORD: example
          POSTGRES_USER: root
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Cache NPM dependencies
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      #- name: Start database
      # run: docker compose up

      - name: Run migrations
        env:
          NODE_ENV: test
          POSTGRES_URL: postgres://root:example@localhost:5432/bloglist_db
          TEST_POSTGRES_URL: postgres://root:example@localhost:5432/bloglist_db
        run: npm run migration:up

      - name: Run local tests
        env:
          NODE_ENV: test
          TEST_POSTGRES_URL: postgres://root:example@localhost:5432/bloglist_db
        run: npm run test

      - name: 'Trigger Deployment'
        if: ${{ github.event_name == 'push' && env.CONDITION == 'false' }}
        run: curl https://api.render.com/deploy/srv-${{secrets.RENDER_SERVICE_ID}}?key=${{secrets.RENDER_API_KEY}}

  tag_release:
    needs: [checkout-and-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        if: ${{ github.event_name == 'push' && env.CONDITION == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
